[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    esphome/AsyncTCP-esphome @ ^2.1.3
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2

# Build flags to handle flash filesystem
board_build.filesystem = spiffs